name: 接続テスト

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - run: pip install selenium webdriver-manager

      - uses: browser-actions/setup-chrome@v1

      - run: python test_selenium.py
